### ISSUE TITLE
Subtasks for OPR

### ISSUE THREAD

**Issue by steull** [OpenEnergyPlatform/oeplatform#1149]
Part of #1033 
- [x] JSON für JavaScript
- [x] Kategorie identifizieren
- [x] Vorschlag für jedes Feld als Variable im vorgegebenen Schema speichern
- [x] Pfeile hinzufügen, welche zum nächsten Feld springen aber der Inalt des Vorschlags nicht verloren geht
- [x] Anzeigen, dass das jeweilige Feld überprüft wurde
- [x] Automatisches Erstellen der Summary
- [x] Sind alle Felder überprüft worden, kann die Summary versendet werden
- [x] fix missing migrations

# Bugs
- [x] Fix - forever disabled "Submit Summary" button
- [x] Fix - show initial content of general tab on page load
- [ ] Fix - Switch tabs when finishing review for all fields in current category
- [x] category naming is not consistent with the mockups (on figma)

# Improvements
- [x] Current datamodel is not production ready ... review structure and add minimal content
- [ ] The data model stores the current review and the completed review (save or submit) ... when a review is opened, it must be generated from the data model and show all fields that have already been reviewed. .... The reviewer or contributor needs this to resume review work or look up the detailed results of completed reviews and possibly reopen the review. .... The data model should be the only source from which a started/completed review can be loaded.
- [x] store revirewer (user) in peerrevirew database table 
- [x] store contributor (user) in peerrevirew database table 
- [x] Improve processing of complete metadata into categories  @Darynarli 
- [x] Improve field paths in categories / or keep it and introduce visible field name to avoide to show the full path as name .... use schema.json title field for the field names @Darynarli

**Comment by christian-rli** [comment]
- [] On data page 
  - [] new tab "Review"
  - [] introduction of new role reviewer
  - [] blocking of review button for other reviewer once review was started
  - [] change colors based on state (not reviewed, in review, reviewed)
- [] menu navigation in review
  - [] clear fields when field is selected
  - [] clear fields when new tab is selected
  - [] include description and example for every field
  - [] indicate open fields in tab with little dot
  - [] indicate overall progress with percentage
  - [] show content of reviewer suggestion on left side
  - [] define which fields require certain input, therefore show red no button, then implement
- [] summary page
  - [] pretty table that summarizes all reviewer input
  - [] tabs or filter buttons for (review missing, rejected, suggestions, accepted)

**Comment by christian-rli** [comment]
@Darynarli The following are some notes on the review process itself and its implementation to help you take over the task.

The review process when finally implemented should work in following way. A user can, after uploading a table, request a review. Users with the role reviewer may then perform the review. The contributor may accept reviewer suggestion or refuse them. Changes will be written to the metadata upon the conclusion of the review.

The review consists of a a manual audit of all user input in the metadata. The original input may be accepted, a change suggested or full out rejected. Rejections are only reserved for cases where an input is incompatible with the OEP, namely a dataset license that is not open. Therefore the reject button is only to be shown there. Metadata here refers to the [latest json standard](https://github.com/OpenEnergyPlatform/oemetadata/tree/develop/metadata/latest) defined in the oemetadata repository.

The metadata comes as JSON from the backend, it is preprocessed in django for the display in Javascript on the page. Currently the page is generated from the metadata itself. The problem with that is that context is missing. Specifically what's missing is 
- The description of the field, which is to be displayed as a helpful text to the reviewer
- A proper display title of the field (e.g. "Language" instead of "language")
- A badge (if all fields of a badge are filled, a dataset gets a corresponding badge)

All of that information is in the schema.json of the oemetadata in this branch https://github.com/OpenEnergyPlatform/oemetadata/pull/117 (to be merged in the next release, but please use the schema of this branch here already). The goal is to still generate the html page from the metadata of the backend, but to take the additional information from the schema file.

Currently, the field review works on a proof of concept level and with some bugs. It will generate some json data with all reviewer input and display it in the summary tab. The JSON is generated within javascript and passed back into the backend when "submit summary" is clicked (only possible after all fields are reviewed). The review-JSON has its own format, defined by @steull . It's well thought out overall, but you may introduce changes if the current format creates problems in the implementation.

The next steps should be to create a fully working review click-through experience and to pass back a valid json string. See the check boxes above. The review needs to be stored in the database. Details on that need to be discussed with @jh-RLI . After all of that works, the contributor page can be implemented, which can mostly be a copy of the reviewer page showing suggestions by the reviewer to be accepted or declined. Additionally, after submission, the metadata of the table will be changed (according to any changed metadata, the badge will be updated if applicable, plus information on review itself is updated). Final steps of the implementation aren't fully defined yet. Feel free to come up with pragmatic solutions and ask for feedback. 

As always, ask if anything is unclear.

**Comment by Darynarli** [comment]
Hi. I have some questions @jh-RLI @christian-rli 

1. Who can start Start Open Peer Review Process?
2. Who are users with a review role?
3. How the whole process happens, I can not fully understand. Now, when I go to the table, I see the Start Open Peer Review Process button. Clicking this button opens a page with data divided into categories, buttons and Review Box. Is this page of a reviewer or a user?
4. Where can I see requests for review? In Review Box?
5. What is badge?

**Comment by Darynarli** [comment]
I understand that I need to do:

1. buttons:

- [ ] save review progress: saves
- [ ] Submit summary: redirects to the summary page
- [ ] rejected: should only be with fields that have a license

2. summary page:

- [ ] categories missing: number of review missing; what category; which field, which value
- [ ] categories rejected: number of review rejected; what category; which field, which value
- [ ] suggestions categories: number of review suggestions; what category; which field, which value
- [ ] accepted categories: number of review accepted; what category; which field, which value

3. percentage progress on the summary page
4. after submit summary page and rechecking, there should be a send review button that sends a proposal to the author of the table (the author may or may not accept the proposal)
5. the article was not appreciated, pending review, or appreciated. If pending review or appreciated - re-evaluation can not be already. If appreciated - must be the author (who was appreciated)
6. on the profile page tables add table status
7. the function of saving reviews in the database

Right?

**Comment by Darynarli** [comment]
I have several ideas for the development of the oep and usability community and the review process itself:
_Community building:_

- create general guidelines for participation in the OEP. For example, how it is recommended to create topics - tables or how to handle situations when the author of the topic does not agree with the moderator's corrections and the moderator insists on their correctness, the algorithm of actions in such situations.
- connect an open source forum (for describing and discussing each topic; ideas, conducting polls)
- create a discord server and convenient communication with the community (flexible structure of channels for different purposes; setting access rights for different categories of users)
- creating a user rating. (User rating can be displayed as the number of points that the user earns for their activity. Points can be received for publishing new topics, forum posts, comments, as well as for participating in discussions and other activities in the community. Rating allows you to evaluate the user's contribution to community and its activity in it.In the future, active users with a good reputation may receive the right to moderation.)
as an option, you can make it possible to leave a short comment before sending, which, for example, is missing in the data or the general impression
- you can add the ability after leaving a review to add the function of comments on the assessment and the ability to edit the assessment (for example, requesting access now from the OEP staff, and in the future from the moderators with the highest rating)as an option, you can make it possible to leave a short comment before sending, which, for example, is missing in the data or the general impression
- you can add the ability after leaving a review to add the function of comments on the assessment and the ability to edit the assessment (for example, requesting access now from the OEP staff, and in the future from the moderators with the highest rating)

_For example_, in Wikipedia's rating and moderation system, users can edit articles, leave comments, and make suggestions for improvement. Each article has a discussion page for users to debate and discuss its content. Moderation is conducted by the community, and any registered user can edit articles and become a moderator.

To be an active moderator, a user must: 

- Achieve a certain reputation level. 
- Demonstrate good editing skills and follow Wikipedia's rules. 
- Participate in discussions and decision-making. 

Wikipedia also has a rating system based on user activity and usefulness, represented by stars, which depends on the number and quality of contributions made. This system allows the community to manage content and maintain high article quality while providing opportunities for interaction and discussion 

_UI & UX_
-  Add the ability to sign in and register an account using sign in with google, facebook
- Automation. Consider code that will auto-moderate topic metadata. For example, check for obscene language or malicious links. In the future, check links with information, for example, to research and find plagiarism in a common database. Or check the description metadata for the entire site database.
-  Make filtering by table rating, creation time. Add the ability to like tables on the site.
https://openenergy-platform.org/dataedit/view/economy

**Comment by jh-RLI** [comment]
1. Contributor uploads data  -> table is in model draft -> reviewer can start review via button on table detail page

**Comment by jh-RLI** [comment]
Regarding:
> I have several ideas for the development of the oep and usability community and the review process itself:
Community building:
> _UI & UX_

Good ideas but we have to focus on the current features :) Lets first build a stable OEP with core funtionality and then improve it later. I suggested to move these comments into multiple new issues or use create a discussion on github :)

**Comment by jh-RLI** [comment]
For now just improve the visible sections (general, .....) and add the title, description and example to the review box. ALso you can improve the function that created the sections in the django view. Next steps follow after that.  

![image](https://user-images.githubusercontent.com/38939526/231463636-6ae27fed-6e0c-4566-8e8f-a5f059d890b0.png)

Update this view:
https://github.com/OpenEnergyPlatform/oeplatform/blob/3b2f8a5c3c50ac018fb499b4d56c3279873e4396/dataedit/views.py#L1832-L1944

**Comment by jh-RLI** [comment]
@Darynarli For now, improve only the visible sections (General, .....) and add the title, description and example to the review box. You can also improve the function that creates the sections in the Django view. The next steps follow afterwards.  

![image](https://user-images.githubusercontent.com/38939526/231464375-1ae9deda-0a3e-40aa-95d2-14d0dda71409.png)

Update this view:
https://github.com/OpenEnergyPlatform/oeplatform/blob/3b2f8a5c3c50ac018fb499b4d56c3279873e4396/dataedit/views.py#L1832-L1944

**Comment by jh-RLI** [comment]
@Darynarli 
I have two small things i just noticed on the reviewer view.

## 1. The reviewer box is not reset if one proceeds to the next field:
- click on id fiel in general keys
- click suggest in reviewer box
- click Name field 
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/a55532d9-dbbd-4b16-8ba8-72ed4f707edb)

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/64a08c4e-f6e8-499a-8bb3-183b35f6800e)



The reviewer box should be reset if next field is selected. By reset, i mean should look like this after the user select the next field:
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/880c026f-c62e-4b33-b712-e957e381b5f4)


## 2. The suggested values should be visible below the original values
- Once the user entered a value suggestion and clicks the Save comment/ new value button, the suggestion must be visible in the related field box.
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/a30d4c10-788e-419c-b8cc-510e1483c282)

**Comment by jh-RLI** [comment]
@Darynarli I found two small things on the reviewer view:

## 1. Value Suggestions must be visible below the orignal value
- If a reviewer suggest a new value, it must be visible in the related field box after the Save button is clicked:
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/61d9677f-f0fd-40fd-8d8d-f286a2fad3a0)

## 2. Reset the reviewer box onces the next field is selected.
(i think there is already a js function available)
- If the user clicks a field and suggests or rejects a value and then navigates to the next field the reviewer box is not rest.
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/c66c2ba6-7361-4fd3-a1c4-d473d63e120b)

![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/eae53cdf-328d-494a-90b8-1251d131d30a)

What i mean by reset. The box should look like this if the user selects the next field:
![image](https://github.com/OpenEnergyPlatform/oeplatform/assets/38939526/e11d17c3-1391-4a9f-8aec-21f6cc452429)

**Comment by Darynarli** [comment]
1. On the contributor's page for an excessive suggested value. Should this also be on the reviewer page?
2. Now when you go to this area, the comments and suggestions fields become empty

**Comment by jh-RLI** [comment]
1. Can you explain more what you mean here?
2.  Great, actually the input fields should not be visible when the next field is displayed in the review field. Maybe that's what you mean? 

It should work like this:
  1. user clicks field
  2. reviewer box shows details and 3 button
  3. user clicks suggestions and the input fields are shown
  4. user confirms input 
  5. reviewer box shows info of the next field and 3 button !the input fields are no longer visible! until suggestion or deny is clicked again.

**Comment by Darynarli** [comment]
1. what you described above in paragraph 1 works on the contributor page. That is, the ReviewSuggestion is displayed. Should it also work on the reviewer page?
2. yes, that's how it works now. I meant it

**Comment by jh-RLI** [comment]
1. Yes, this is a good point and should work the same way in the reviewer view. When the reviewer applies a suggestion, it should be displayed below the original value.
2.  Very :)

**Comment by Darynarli** [comment]
> 1. Yes, this is a good point and should work the same way in the reviewer view. When the reviewer applies a suggestion, it should be displayed below the original value.
okey, i will make it
