### ISSUE TITLE
Data versioning is not visibly in place

### ISSUE THREAD

**Issue by Bachibouzouk** [OpenEnergyPlatform/oeplatform#456]
There are many issues linked to this issue, I opened this one to have one place to look at

- [x] Design suggestions #147

- [x] Design suggestions #134

- [x] Link between website and DB for versioning #149

- [x] Add rows in table using recline #109

- [x] Make table creation more robust by checking for duplicated column names and PK field #1032

**Comment by jh-RLI** [comment]
@Ludee @wingechr Interesting issue, the linked issues also provide a good idea of what happened to the "edit table" function. My understanding is that editing is possible via the API and it was not entirely clear how to proceed with the UI to edit a table. So it was removed and suggested to implement it again later. What do you think about this?

**Comment by wingechr** [comment]
it is possible with the API, **BUT...**

there is a very big underlying problem:

updating rows only works if the table has a numerical  `id` column as primary key. 
But this is not being enforced (you can create tables without that), see also #739

This should be addressed first before we enable anything on the UI, because it will just cause more confusion and problems.

**Comment by wingechr** [comment]
@jh-RLI actually, this issue is not closed by the mentioned pull request(the id column is just one part of it)

**Comment by jh-RLI** [comment]
Yea that's true I just wanted to link it and GitHub assumes it will close :/ I will just update the first comment and link the PR there.
